# Use this in your UnturnedImages/config.yaml file
- Id: "51910-51916;51920-51921;51923-51928" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2899033069/items/{ItemId}.png" # The repository of the override.