# Use this in your UnturnedImages/config.yaml file
- Id: "41000-41033" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2964695228/vehicles/{ItemId}.png" # The repository of the override.