# Use this in your UnturnedImages/config.yaml file
- Id: "2006020060;20070-20071;20080-20081" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/913321090/items/{ItemId}.png" # The repository of the override.