# Use this in your UnturnedImages/config.yaml file
- Id: "59000" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1751896219/vehicles/{ItemId}.png" # The repository of the override.