# Use this in your UnturnedImages/config.yaml file
- Id: "40001-40002" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2932535655/vehicles/{ItemId}.png" # The repository of the override.