# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "3769784773" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/workshop/3769784773/vehicles/{VehicleId}.png" # The repository of the override.