# Use this in your UnturnedImages/config.yaml file
- Id: "7031" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2772030264/vehicles/{ItemId}.png" # The repository of the override.