# Use this in your UnturnedImages/config.yaml file
- Id: "22231-22232;22236-22237" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2820727801/items/{ItemId}.png" # The repository of the override.