# Use this in your UnturnedImages/config.yaml file
- Id: "70507050;70567056;40100-40101;41000-41003;4100741007;50056-50057" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3483724786/vehicles/{ItemId}.png" # The repository of the override.