# Use this in your UnturnedImages/config.yaml file
- Id: "22292-22294;2229922299;22309-22310;2231222312;22315-22316;22320-22321" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2867590772/items/{ItemId}.png" # The repository of the override.