# Use this in your UnturnedImages/config.yaml file
- Id: "8950-8977;50100-50103" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1493773706/items/{ItemId}.png" # The repository of the override.