# Use this in your UnturnedImages/config.yaml file
- Id: "49000-49002" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1751896219/items/{ItemId}.png" # The repository of the override.