# Use this in your UnturnedImages/config.yaml file
- Id: "21080-21103" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/913321090/vehicles/{ItemId}.png" # The repository of the override.